package com.aryaxzell.keyglass.ui.localization

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf
import java.util.Locale

class Strings(
    val languageCode: String,
    // Navigation & Common
    val back: String,
    val cancel: String,
    val done: String,
    val close: String,
    val save: String,
    val search: String,
    val retry: String,

    // Dashboard
    val appTitle: String,
    val appSubtitle: String,
    val keyboardStatus: String,
    val statusActive: String,
    val statusEnabled: String,
    val statusDisabled: String,
    val statusActiveSub: String,
    val statusEnabledSub: String,
    val statusDisabledSub: String,
    val enableInSettings: String,
    val switchToKeyGlass: String,
    val batteryBannerTitle: String,
    val batteryBannerDesc: String,
    val disableOptimization: String,
    val tryKeyboardHeader: String,
    val tryKeyboardPlaceholder: String,
    val tryKeyboardFooter: String,
    val customizationHeader: String,
    val appearanceTitle: String,
    val appearanceSubtitle: String,
    val keyboardThemesTitle: String,
    val keyboardThemesSubtitle: String,
    val typingBehaviorTitle: String,
    val typingBehaviorSubtitle: String,
    val gesturesTitle: String,
    val gesturesSubtitle: String,
    val personalDictionaryTitle: String,
    val personalDictionarySubtitle: String,
    val systemSupportHeader: String,
    val generalTitle: String,
    val generalSubtitle: String,
    val aboutTitle: String,
    val aboutSubtitle: String,

    // Keyboard Customization
    val customImageHeader: String,
    val chooseImageBtn: String,
    val changeImageBtn: String,
    val removeCustomImageBtn: String,
    val presetThemesHeader: String,
    val presetGlassDark: String,
    val presetGlassLight: String,
    val presetFootball: String,
    val presetCyberpunk: String,
    val presetSunset: String,
    val presetOcean: String,
    val presetEmerald: String,
    val presetAurora: String,
    val presetMidnight: String,
    val presetPastelBloom: String,
    val backgroundDarknessHeader: String,
    val backgroundDarknessDesc: String,
    val previewBeforeConfirm: String,
    val applyThemeBtn: String,
    val themeAppliedSuccess: String,
    val resetToDefaultTheme: String,

    // Appearance
    val interfaceTheme: String,
    val themeLight: String,
    val themeDark: String,
    val themeSystem: String,
    val accentColor: String,
    val cornerRadius: String,
    val radiusSharp: String,
    val radiusMedium: String,
    val radiusRound: String,
    val radiusPill: String,
    val typographyHeader: String,
    val useInterFont: String,
    val useInterFontDesc: String,
    val realtimePreview: String,

    // Typing Behavior
    val intelligenceHeader: String,
    val predictiveBar: String,
    val predictiveBarDesc: String,
    val typoCorrection: String,
    val typoCorrectionDesc: String,
    val keyPopupBubble: String,
    val keyPopupBubbleDesc: String,
    val hapticSoundHeader: String,
    val hapticFeedback: String,
    val hapticFeedbackDesc: String,
    val vibrationIntensity: String,
    val soundFeedback: String,
    val soundFeedbackDesc: String,
    val soundVolume: String,
    val capitalizationHeader: String,
    val autoCapitalization: String,
    val autoCapitalizationDesc: String,
    val typingLanguagesHeader: String,
    val englishLanguage: String,
    val indonesianLanguage: String,

    // Gestures
    val trackpadHeader: String,
    val trackpadSensitivity: String,
    val trackpadDesc: String,
    val keyHoldTimingHeader: String,
    val longPressDelay: String,
    val longPressDesc: String,

    // Dictionary
    val addWordBtn: String,
    val emptyDictionaryTitle: String,
    val emptyDictionaryDesc: String,
    val addCustomWordTitle: String,
    val whitelistedWordsHeader: String,
    val dictionaryFooter: String,
    val enterWordPrompt: String,
    val wordLabel: String,
    val shortcutLabel: String,
    val saveWordBtn: String,

    // General
    val companionLanguageHeader: String,
    val languageSystem: String,
    val languageEnglish: String,
    val languageIndonesian: String,
    val backupHeader: String,
    val exportJsonTitle: String,
    val exportJsonSubtitle: String,
    val importJsonTitle: String,
    val importJsonSubtitle: String,
    val resetHeader: String,
    val resetAllSettingsTitle: String,
    val resetDialogTitle: String,
    val resetDialogMessage: String,
    val resetConfirmBtn: String,
    val applySettingsBtn: String,
    val toastCopied: String,
    val toastResetDone: String,
    val toastImportDone: String,
    val toastInvalidJson: String,

    // About
    val appInfoHeader: String,
    val appVersionLabel: String,
    val nightlyBadge: String,
    val checkForUpdates: String,
    val checkingUpdates: String,
    val architectureLabel: String,
    val whatsNewTitle: String,
    val privacyPromiseTitle: String,
    val developerHeader: String,
    val githubProfile: String,
    val sourceCodeTitle: String,
    val reportIssueTitle: String,
    val updateModalTitle: String,
    val downloadingUpdate: String,
    val extractingUpdate: String,
    val updateReadyTitle: String,
    val updateReadyDesc: String,
    val installUpdateBtn: String,
    val openGitHubActionsBtn: String,
    val noUpdateAvailable: String,
    val updateError: String,

    // Search
    val searchPlaceholder: String,
    val allSettingsHeader: String,
    val resultsHeader: String,

    // Onboarding
    val welcomeTitle: String,
    val welcomeDesc: String,
    val step1Title: String,
    val step1Desc: String,
    val step2Title: String,
    val step2Desc: String,
    val step3Title: String,
    val step3Desc: String,
    val getStartedBtn: String
)

val EnglishStrings = Strings(
    languageCode = "en",
    back = "Back",
    cancel = "Cancel",
    done = "Done",
    close = "Close",
    save = "Save",
    search = "Search",
    retry = "Retry",

    appTitle = "KeyGlass",
    appSubtitle = "iOS-Style Keyboard",
    keyboardStatus = "Keyboard Status",
    statusActive = "KeyGlass is Active",
    statusEnabled = "KeyGlass is Enabled",
    statusDisabled = "KeyGlass is Disabled",
    statusActiveSub = "Ready to use in any app",
    statusEnabledSub = "Tap Switch to make it active",
    statusDisabledSub = "Enable in system settings to use",
    enableInSettings = "Enable in Settings",
    switchToKeyGlass = "Switch to KeyGlass",
    batteryBannerTitle = "Keep KeyGlass Responsive",
    batteryBannerDesc = "Android battery optimization can sometimes cause input lag when opening keyboards. Allowing background exemption keeps typing instant.",
    disableOptimization = "Disable Optimization",
    tryKeyboardHeader = "Try Keyboard",
    tryKeyboardPlaceholder = "Tap to test KeyGlass...",
    tryKeyboardFooter = "Tap anywhere inside the card above to immediately trigger the KeyGlass keyboard.",
    customizationHeader = "Customization",
    appearanceTitle = "Appearance",
    appearanceSubtitle = "Theme, corner radius, accent color, fonts",
    keyboardThemesTitle = "Keyboard Customization",
    keyboardThemesSubtitle = "Custom photo background, themes & dimming slider",
    typingBehaviorTitle = "Typing Behavior",
    typingBehaviorSubtitle = "Autocorrect, predictions, sound, haptics",
    gesturesTitle = "Gestures",
    gesturesSubtitle = "Space bar cursor, long-press duration",
    personalDictionaryTitle = "Personal Dictionary",
    personalDictionarySubtitle = "Manage whitelisted words",
    systemSupportHeader = "System & Support",
    generalTitle = "General",
    generalSubtitle = "Language, backup, reset settings",
    aboutTitle = "About KeyGlass",
    aboutSubtitle = "Nightly build, developer, updates",

    customImageHeader = "Custom Photo Background",
    chooseImageBtn = "Choose Image from Gallery",
    changeImageBtn = "Change Image",
    removeCustomImageBtn = "Remove Custom Image",
    presetThemesHeader = "Preset Themes",
    presetGlassDark = "Glass Dark",
    presetGlassLight = "Glass Light",
    presetFootball = "Football Stadium",
    presetCyberpunk = "Cyberpunk Neon",
    presetSunset = "Sunset Sky",
    presetOcean = "Deep Ocean",
    presetEmerald = "Emerald Glass",
    presetAurora = "Aurora Borealis",
    presetMidnight = "Tokyo Midnight",
    presetPastelBloom = "Pastel Bloom",
    backgroundDarknessHeader = "Background Dimming / Contrast",
    backgroundDarknessDesc = "Adjust darkness overlay so key letters stay crisp and easy to read",
    previewBeforeConfirm = "Live Keyboard Real-time Preview",
    applyThemeBtn = "Apply & Save Theme",
    themeAppliedSuccess = "Keyboard theme applied successfully!",
    resetToDefaultTheme = "Reset to Default Glass",

    interfaceTheme = "Interface Theme",
    themeLight = "Light Mode",
    themeDark = "Dark Mode",
    themeSystem = "Follow System",
    accentColor = "Keyboard Accent Color",
    cornerRadius = "Key Corner Radius",
    radiusSharp = "Sharp",
    radiusMedium = "Medium",
    radiusRound = "Round",
    radiusPill = "Pill",
    typographyHeader = "Typography",
    useInterFont = "Use SF Pro Bold Font",
    useInterFontDesc = "Toggle between Apple-style SF Pro Bold typography and system font",
    realtimePreview = "Realtime Preview",

    intelligenceHeader = "Intelligence & Suggestions",
    predictiveBar = "Predictive Text Bar",
    predictiveBarDesc = "Display next-word and candidate suggestions above keys",
    typoCorrection = "Typo Correction",
    typoCorrectionDesc = "Automatically replace detected typos on spacebar",
    keyPopupBubble = "Key Popup Bubble",
    keyPopupBubbleDesc = "Enlarge pressed character in spring bubble",
    hapticSoundHeader = "Haptic & Sound Feedback",
    hapticFeedback = "Haptic Feedback",
    hapticFeedbackDesc = "Tactile vibration tick on every keystroke",
    vibrationIntensity = "Vibration Intensity",
    soundFeedback = "Sound Feedback",
    soundFeedbackDesc = "Soft pop tone on keystrokes",
    soundVolume = "Sound Volume",
    capitalizationHeader = "Capitalization",
    autoCapitalization = "Auto-Capitalization",
    autoCapitalizationDesc = "Capitalize the first letter of each sentence",
    typingLanguagesHeader = "Typing Languages",
    englishLanguage = "English (US)",
    indonesianLanguage = "Indonesian (Bahasa Indonesia)",

    trackpadHeader = "Trackpad Cursor Control",
    trackpadSensitivity = "Cursor Sensitivity",
    trackpadDesc = "Slide your thumb left or right along the space bar to move the text insertion point smoothly. Higher sensitivity moves the cursor faster.",
    keyHoldTimingHeader = "Key Hold Timing",
    longPressDelay = "Long-Press Delay",
    longPressDesc = "The amount of time required to hold a key before accented alternatives appear above it. Shorter times respond quicker.",

    addWordBtn = "+ Add",
    emptyDictionaryTitle = "No Words in Dictionary",
    emptyDictionaryDesc = "Words you add here will never be auto-corrected or flagged as typos.",
    addCustomWordTitle = "Add Custom Word",
    whitelistedWordsHeader = "Whitelisted Words",
    dictionaryFooter = "Tap the trash icon to remove a word from your personal dictionary.",
    enterWordPrompt = "Enter a word, slang term, or name to whitelist:",
    wordLabel = "Word / Acronym",
    shortcutLabel = "Shortcut (Optional)",
    saveWordBtn = "Save Word",

    companionLanguageHeader = "Companion App Language",
    languageSystem = "Follow System",
    languageEnglish = "English",
    languageIndonesian = "Bahasa Indonesia",
    backupHeader = "Backup & Transfer",
    exportJsonTitle = "Export Settings to JSON",
    exportJsonSubtitle = "Copy settings configuration to clipboard",
    importJsonTitle = "Import Settings from JSON",
    importJsonSubtitle = "Paste a saved configuration to restore",
    resetHeader = "Reset",
    resetAllSettingsTitle = "Reset All Settings",
    resetDialogTitle = "Reset Settings?",
    resetDialogMessage = "All appearance and typing customization will revert to their original values. Your Personal Dictionary words will not be deleted.",
    resetConfirmBtn = "Reset to Defaults",
    applySettingsBtn = "Apply Settings",
    toastCopied = "Settings copied to clipboard",
    toastResetDone = "Settings restored to defaults",
    toastImportDone = "Settings restored successfully",
    toastInvalidJson = "Invalid JSON format",

    appInfoHeader = "Application Info",
    appVersionLabel = "KeyGlass Nightly",
    nightlyBadge = "NIGHTLY",
    checkForUpdates = "Check for Updates",
    checkingUpdates = "Checking GitHub...",
    architectureLabel = "Architecture",
    whatsNewTitle = "What's New in KeyGlass",
    privacyPromiseTitle = "KeyGlass Privacy Promise",
    developerHeader = "Developer",
    githubProfile = "GitHub Profile",
    sourceCodeTitle = "KeyGlass Source Code",
    reportIssueTitle = "Report an Issue",
    updateModalTitle = "Nightly Update",
    downloadingUpdate = "Downloading update package...",
    extractingUpdate = "Extracting APK archive...",
    updateReadyTitle = "Update Ready",
    updateReadyDesc = "Nightly build has been downloaded and extracted. Tap below to launch installer.",
    installUpdateBtn = "Install Update",
    openGitHubActionsBtn = "Open GitHub Actions",
    noUpdateAvailable = "You have the latest Nightly build.",
    updateError = "Failed to fetch update automatically.",

    searchPlaceholder = "Search settings, features...",
    allSettingsHeader = "All Settings",
    resultsHeader = "Results",

    welcomeTitle = "Welcome to KeyGlass",
    welcomeDesc = "iOS-style glass keyboard for Android with fast offline intelligence and fluid spring physics.",
    step1Title = "1. Enable Keyboard",
    step1Desc = "Turn on KeyGlass in Android System Settings",
    step2Title = "2. Switch Keyboard",
    step2Desc = "Select KeyGlass as your active input method",
    step3Title = "3. Ready to Type",
    step3Desc = "Start typing with iOS aesthetics and smart autocorrect",
    getStartedBtn = "Get Started"
)

val IndonesianStrings = Strings(
    languageCode = "in",
    back = "Kembali",
    cancel = "Batal",
    done = "Selesai",
    close = "Tutup",
    save = "Simpan",
    search = "Cari",
    retry = "Coba Lagi",

    appTitle = "KeyGlass",
    appSubtitle = "Keyboard Bergaya iOS",
    keyboardStatus = "Status Keyboard",
    statusActive = "KeyGlass Aktif",
    statusEnabled = "KeyGlass Diaktifkan",
    statusDisabled = "KeyGlass Dinonaktifkan",
    statusActiveSub = "Siap digunakan di semua aplikasi",
    statusEnabledSub = "Ketuk Ganti untuk mengaktifkan",
    statusDisabledSub = "Aktifkan di pengaturan sistem untuk menggunakan",
    enableInSettings = "Aktifkan di Pengaturan",
    switchToKeyGlass = "Ganti ke KeyGlass",
    batteryBannerTitle = "Jaga KeyGlass Tetap Responsif",
    batteryBannerDesc = "Optimasi baterai Android dapat menyebabkan lag saat membuka keyboard. Mengizinkan pengecualian latar belakang menjaga pengetikan tetap instan.",
    disableOptimization = "Nonaktifkan Optimasi",
    tryKeyboardHeader = "Coba Keyboard",
    tryKeyboardPlaceholder = "Ketuk untuk mencoba KeyGlass...",
    tryKeyboardFooter = "Ketuk di mana saja di dalam kartu di atas untuk langsung memunculkan keyboard KeyGlass.",
    customizationHeader = "Kustomisasi",
    appearanceTitle = "Tampilan",
    appearanceSubtitle = "Tema, radius sudut, warna aksen, font",
    keyboardThemesTitle = "Kustomisasi Keyboard",
    keyboardThemesSubtitle = "Foto kustom latar belakang, preset tema & slider kontras",
    typingBehaviorTitle = "Perilaku Mengetik",
    typingBehaviorSubtitle = "Koreksi otomatis, prediksi, suara, haptik",
    gesturesTitle = "Gestur",
    gesturesSubtitle = "Kursor bilah spasi, durasi tekan lama",
    personalDictionaryTitle = "Kamus Pribadi",
    personalDictionarySubtitle = "Kelola kosakata yang diizinkan",
    systemSupportHeader = "Sistem & Dukungan",
    generalTitle = "Umum",
    generalSubtitle = "Bahasa, cadangan, reset pengaturan",
    aboutTitle = "Tentang KeyGlass",
    aboutSubtitle = "Versi Nightly, pengembang, pembaruan",

    customImageHeader = "Foto / Gambar Kustom",
    chooseImageBtn = "Pilih Gambar dari Galeri",
    changeImageBtn = "Ganti Gambar",
    removeCustomImageBtn = "Hapus Gambar Kustom",
    presetThemesHeader = "Pilihan Tema Keyboard",
    presetGlassDark = "Kaca Gelap (Glass Dark)",
    presetGlassLight = "Kaca Terang (Glass Light)",
    presetFootball = "Stadion Sepak Bola (Football)",
    presetCyberpunk = "Neon Cyberpunk",
    presetSunset = "Langit Senja (Sunset)",
    presetOcean = "Laut Biru (Deep Ocean)",
    presetEmerald = "Kaca Zamrud (Emerald)",
    presetAurora = "Cahaya Aurora",
    presetMidnight = "Malam Tokyo (Midnight)",
    presetPastelBloom = "Bunga Pastel (Pastel)",
    backgroundDarknessHeader = "Tingkat Kegelapan / Kecerahan Latar",
    backgroundDarknessDesc = "Sesuaikan kegelapan lapisan agar huruf tombol tetap sangat jelas dan nyaman dibaca",
    previewBeforeConfirm = "Pratinjau Langsung Keyboard Real-Time",
    applyThemeBtn = "Terapkan & Simpan Tema",
    themeAppliedSuccess = "Tema keyboard berhasil diterapkan!",
    resetToDefaultTheme = "Kembalikan ke Kaca Default",

    interfaceTheme = "Tema Antarmuka",
    themeLight = "Mode Terang",
    themeDark = "Mode Gelap",
    themeSystem = "Ikuti Sistem",
    accentColor = "Warna Aksen Keyboard",
    cornerRadius = "Radius Sudut Tombol",
    radiusSharp = "Tajam",
    radiusMedium = "Sedang",
    radiusRound = "Bulat",
    radiusPill = "Kapsul",
    typographyHeader = "Tipografi",
    useInterFont = "Gunakan Font SF Pro Bold",
    useInterFontDesc = "Pilih antara tipografi SF Pro Bold bergaya Apple atau font bawaan sistem",
    realtimePreview = "Pratinjau Langsung",

    intelligenceHeader = "Kecerdasan & Saran",
    predictiveBar = "Bilah Teks Prediktif",
    predictiveBarDesc = "Tampilkan kata berikutnya dan saran kata di atas tombol",
    typoCorrection = "Koreksi Salah Ketik",
    typoCorrectionDesc = "Otomatis ganti salah ketik saat menekan spasi",
    keyPopupBubble = "Gelembung Popup Tombol",
    keyPopupBubbleDesc = "Perbesar karakter yang ditekan dengan gelembung pegas",
    hapticSoundHeader = "Umpan Balik Haptik & Suara",
    hapticFeedback = "Umpan Balik Getar (Haptik)",
    hapticFeedbackDesc = "Getaran taktil halus di setiap ketukan tombol",
    vibrationIntensity = "Intensitas Getaran",
    soundFeedback = "Umpan Balik Suara",
    soundFeedbackDesc = "Suara pop lembut saat mengetik",
    soundVolume = "Volume Suara",
    capitalizationHeader = "Kapitalisasi",
    autoCapitalization = "Kapitalisasi Otomatis",
    autoCapitalizationDesc = "Kapitalkan huruf pertama di setiap kalimat",
    typingLanguagesHeader = "Bahasa Pengetikan",
    englishLanguage = "Inggris (US)",
    indonesianLanguage = "Indonesia (Bahasa Indonesia)",

    trackpadHeader = "Kontrol Kursor Trackpad",
    trackpadSensitivity = "Sensitivitas Kursor",
    trackpadDesc = "Geser ibu jari ke kiri atau kanan di bilah spasi untuk memindahkan titik kursor secara halus. Sensitivitas lebih tinggi menggerakkan kursor lebih cepat.",
    keyHoldTimingHeader = "Waktu Tahan Tombol",
    longPressDelay = "Durasi Tekan Lama",
    longPressDesc = "Waktu yang dibutuhkan untuk menahan tombol sebelum alternatif karakter aksen muncul di atasnya. Waktu lebih singkat merespons lebih cepat.",

    addWordBtn = "+ Tambah",
    emptyDictionaryTitle = "Belum Ada Kata di Kamus",
    emptyDictionaryDesc = "Kata yang Anda tambahkan di sini tidak akan pernah dikoreksi otomatis atau dianggap salah ketik.",
    addCustomWordTitle = "Tambah Kata Kustom",
    whitelistedWordsHeader = "Daftar Kata Diizinkan",
    dictionaryFooter = "Ketuk ikon tempat sampah untuk menghapus kata dari kamus pribadi Anda.",
    enterWordPrompt = "Masukkan kata, istilah gaul, atau nama untuk diizinkan:",
    wordLabel = "Kata / Singkatan",
    shortcutLabel = "Pintasan (Opsional)",
    saveWordBtn = "Simpan Kata",

    companionLanguageHeader = "Bahasa Aplikasi Pendamping",
    languageSystem = "Ikuti Sistem",
    languageEnglish = "English",
    languageIndonesian = "Bahasa Indonesia",
    backupHeader = "Cadangan & Pemindahan",
    exportJsonTitle = "Ekspor Pengaturan ke JSON",
    exportJsonSubtitle = "Salin konfigurasi pengaturan ke papan klip",
    importJsonTitle = "Impor Pengaturan dari JSON",
    importJsonSubtitle = "Tempel konfigurasi tersimpan untuk memulihkan",
    resetHeader = "Atur Ulang",
    resetAllSettingsTitle = "Atur Ulang Semua Pengaturan",
    resetDialogTitle = "Atur Ulang Pengaturan?",
    resetDialogMessage = "Semua kustomisasi tampilan dan pengetikan akan kembali ke nilai awal. Kosakata Kamus Pribadi Anda tidak akan dihapus.",
    resetConfirmBtn = "Kembalikan ke Awal",
    applySettingsBtn = "Terapkan Pengaturan",
    toastCopied = "Pengaturan disalin ke papan klip",
    toastResetDone = "Pengaturan dikembalikan ke setelan awal",
    toastImportDone = "Pengaturan berhasil dipulihkan",
    toastInvalidJson = "Format JSON tidak valid",

    appInfoHeader = "Info Aplikasi",
    appVersionLabel = "KeyGlass Nightly",
    nightlyBadge = "NIGHTLY",
    checkForUpdates = "Periksa Pembaruan",
    checkingUpdates = "Memeriksa GitHub...",
    architectureLabel = "Arsitektur",
    whatsNewTitle = "Apa yang Baru di KeyGlass",
    privacyPromiseTitle = "Janji Privasi KeyGlass",
    developerHeader = "Pengembang",
    githubProfile = "Profil GitHub",
    sourceCodeTitle = "Kode Sumber KeyGlass",
    reportIssueTitle = "Laporkan Masalah",
    updateModalTitle = "Pembaruan Nightly",
    downloadingUpdate = "Mengunduh paket pembaruan...",
    extractingUpdate = "Mengekstrak paket APK...",
    updateReadyTitle = "Pembaruan Siap",
    updateReadyDesc = "Versi Nightly telah diunduh dan diekstrak. Ketuk tombol di bawah untuk memasang.",
    installUpdateBtn = "Pasang Pembaruan",
    openGitHubActionsBtn = "Buka GitHub Actions",
    noUpdateAvailable = "Anda sudah menggunakan versi Nightly terbaru.",
    updateError = "Gagal mengambil pembaruan otomatis dari GitHub.",

    searchPlaceholder = "Cari pengaturan, fitur...",
    allSettingsHeader = "Semua Pengaturan",
    resultsHeader = "Hasil",

    welcomeTitle = "Selamat Datang di KeyGlass",
    welcomeDesc = "Keyboard kaca bergaya iOS untuk Android dengan kecerdasan offline cepat dan fisika pegas yang lancar.",
    step1Title = "1. Aktifkan Keyboard",
    step1Desc = "Aktifkan KeyGlass di Pengaturan Sistem Android",
    step2Title = "2. Pilih Keyboard",
    step2Desc = "Pilih KeyGlass sebagai metode input aktif Anda",
    step3Title = "3. Siap Digunakan",
    step3Desc = "Mulai mengetik dengan estetika iOS dan koreksi otomatis pintar",
    getStartedBtn = "Mulai Sekarang"
)

val LocalStrings = compositionLocalOf { EnglishStrings }

fun getStringsForLanguage(code: String): Strings {
    return when (code.lowercase()) {
        "in", "id", "indonesian" -> IndonesianStrings
        "en", "english" -> EnglishStrings
        else -> {
            val systemLang = Locale.getDefault().language.lowercase()
            if (systemLang == "in" || systemLang == "id") IndonesianStrings else EnglishStrings
        }
    }
}
